/**
 * Uber API
 * Move your app forward with the Uber API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Product {
    /**
     * Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
     */
    productId?: string;

    /**
     * Description of product.
     */
    description?: string;

    /**
     * Display name of product.
     */
    displayName?: string;

    /**
     * Capacity of product. For example, 4 people.
     */
    capacity?: string;

    /**
     * Image URL representing the product.
     */
    image?: string;

}
