/**
 * Uber API
 * Move your app forward with the Uber API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Profile {
    /**
     * First name of the Uber user.
     */
    firstName?: string;

    /**
     * Last name of the Uber user.
     */
    lastName?: string;

    /**
     * Email address of the Uber user
     */
    email?: string;

    /**
     * Image URL of the Uber user.
     */
    picture?: string;

    /**
     * Promo code of the Uber user.
     */
    promoCode?: string;

}
